in_dim: 5
num_cls: 10
pool_type: "sum"
use_jk: false
positive_prior: 0.5

beep:
  seed: 42
  base_explainer: "pgexplainer"
  epochs: 30
  batch_size: 16
  nlayers: 4
  hidden: 64
  lr: 0.001
  size_reg: 1.0
  ent_reg: 1.0
  round1_epochs: 100
  round1_lr: 0.0001
  round: 2
  tau: 0.45
  tau_margin: 0.0001
  std_multiplier: 1.0
  threshold_strategy: "skewness_adjusted"
  alpha0: 0.05
  c: 5.0
  vae_thre: 0.8
  w: 5.0
  base_hparams:
    pgexplainer:
      alpha0: 0.05
      c: 5.0
      w: 5.0
    gsat:
      alpha0: 0.125
      c: 0.25
      w: 0.5
    mixupexplainer:
      alpha0: 0.15
      c: 1.0
      w: 1.0
    proxyexplainer:
      alpha0: 0.05
      c: 5.0
      w: 5.0
    confexplainer:
      alpha0: 0.1
      c: 0.25
      w: 1.0
    goat:
      alpha0: 0.075
      c: 1.5
      w: 3.0
      base_score_cache_dir: "edge_score_cache_goat_best"
      is_undirected: true
      goat_score_transform: "negative"
      goat_undirected_aggr: "max"
    eigsearch:
      alpha0: 0.125
      c: 5.0
      w: 3.0
      base_score_cache_dir: "edge_score_cache_eigsearch"
      is_undirected: true
      eig_epsilon: 0.05
      eig_sparsity: 0.7
      eig_enable_search: false
      eig_max_edges: 1000
      eig_search_max_edges: 100
  enable_second_guided: true
  second_std_multiplier: 1.0
